# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Do not trigger on Pull Request creation
# This setting is sneaky: it 'sticks' when removed
pr: none

# Only trigger once for each merge or individual (manual) commit on the main branch
trigger:
  batch: 'true'
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'apmc-docker'
    repository: 'asoundmove/aicore-devopsproject-webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aicore-apmc-aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s-webapp/application-manifest.yaml'
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'apmc-docker'

# Because were-use the 'latest' tag for new versions of the docker image,
# 'apply' above will not deploy, so we need to 'rollout' as well.
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aicore-apmc-aks'
    namespace: 'default'
    command: 'rollout'
    arguments: 'restart deployment/webapp-deployment'
    useConfigurationFile: false
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'apmc-docker'